services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data:/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  web:
    build: .
    command: bash -c 'npm run generate && npm run migrate && npm run build && npm start'
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  data:
    external: true
